config/routes.rb
Rails.application.routes.draw do

  root 'lists#index'
    
  resources :lists do
	resources :tasks
	end

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :task, presence: true,
                    length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_controller.rb
class ListController < ApplicationController
        def new
	   @list = List.new
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	http_basic_authenticate_with name: "test", password: "passw", except: [:index, :show]	
	
	def index
  	   @lists = List.all
	end 	
	def show
 	   @list = List.find(params[:id])
	end        
	def new
	  @list = List.new
	end
	def edit
	   @list = List.find(params[:id])
	end
        def create
	   @list = List.new(list_params)
 
  	  if @list.save
    	    redirect_to lists_path
 	 else
   	 render 'new'
 	 end
        end
	def update
  	  @list = List.find(params[:id])
 
  	  if @list.update(list_params)
   	 redirect_to @list
  	 else
    	 render 'edit'
  	 end
	end
	def destroy
	  @list = List.find(params[:id])
	  @list.destroy
 
	  redirect_to lists_path
	end
private
  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	http_basic_authenticate_with name: "test", password: "passw", only: :destroy	
	 
	def edit
	    @task = Task.find(params[:id])
	    @list = List.find(params[:list_id])
	end	
	def create
	    @list = List.find(params[:list_id])
	    @task = @list.tasks.create(task_params)
	    redirect_to lists_path
	end
	def update
	    @list = List.find(params[:list_id])
	    @task = Task.find(params[:id])
 	 if @task.update(task_params)
   	 redirect_to lists_path
  	 else
    	 render 'edit'
  	 end
	end
	def destroy
	    @list = List.find(params[:list_id])
	    @task = Task.find(params[:id])
	    @task.destroy
	    redirect_to lists_path
	end
  private
    def task_params
      params.require(:task).permit(:task)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rgarage</title>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="/assets/bootstrap.css" rel="stylesheet">
</head>
<body>
    <h1 align="center"><b>SIMPLE TODO LISTS</b></h1>
    <h2 align="center">FROM RUBY GARAGE</h2>
    <br>
    <div id="taskruby">
      <%= yield %>
    </div>
<div align="center">
    <%= link_to( image_tag("add_bottom_btn.png"), new_list_path) %>
</div>

</body>
</html>

app/views/layouts/application.html_old.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rgarage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="assets/bootstrap.css" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
 
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
 
<% @lists.each do |list| %>



<table class="table-hover1 form-hover" align="center" width="700" style="box-shadow: 0px 0px 1px #000000; border-radius: 0px 0px 10px 10px; margin-bottom: 20px;">
        <tbody>
        <tr style="box-shadow: 0px 0px 2px #28405D; position: relative;" height="50">
          <th style="background-image: url('/assets/bkg_table_head_l.png'); background-repeat: no-repeat;" colspan=3><span id="tablehead"><%= list.title %></span>
          </th>
          <td style="padding-left: 48px; padding-top: 3px; background-image: url('/assets/bkg_table_head_r.png'); background-repeat: no-repeat; width: 120px; ">
            <div class="action-task">
            <%= link_to( image_tag("edit_btn.png"), edit_list_path(list)) %>&nbsp<img src="/assets/line_top_del_ed.png">&nbsp<%= link_to image_tag("del_btn.png"), list_path(list), method: :delete, data: { confirm: 'Are you sure?' } %>
            
            </div>
          </td>
        </tr>
        
        <tr style="height: 50px" background="/assets/bkg_input_add.png">


<%= form_for Task.create, url: list_tasks_path(list), method: :post do |f| %>
          <td style="padding-top: 3px;" align="center"><input type="image" src="/assets/plus.png"></td>
          <td align="right" colspan=2 ><%= f.text_field :task, style: 'height: 32px; width: 530px;', :placeholder => "Start typing here to create a task…" %></td>
          <td style="padding-top: 3px;"><input style="background: url('/assets/add_button.png') no-repeat; border: none; height: 30px; width: 108px; padding: 0px; margin-bottom: 3px;" value="" type="submit"></td>
	<% end %>
        </tr>
<% list.tasks.order("created_at asc").each do |task| %>
        <tr style="border-top: 1px solid #E7EBEA;">  
          <td style="border: 0px; width: 40px;" align="center"><input type="checkbox"></td>
          <td style="border-right: 1px solid #EFDADF; border-left: 1px solid #EFDADF; width: 5px;">&nbsp</td>
          <td style="border: 0px; width: 535px; padding: 16px 22px 16px 16px;"><%= task.task %></td>
          <td style="border-left: 1px solid #E7EBEA; width: auto;" align="center">
            <div class="action-task">
              <input style="margin-right: 11px;" type="image" src="/assets/move_task_btn.png">
              <img style="margin-right: 11px;" src="/assets/line_task_action.png">
              <%= link_to( image_tag("edit_task_btn.png"), edit_list_task_path(task[:list_id], task[:id])) %>
              <img style="margin-right: 11px;" src="/assets/line_task_action.png">
              <%= link_to image_tag("del_task_btn.png"), list_task_path(task[:list_id], task[:id]), method: :delete, data: { confirm: 'Are you sure to delete this task?' } %>
            </div>
          </td>
        </tr>
        <!-- <tr style="border-top: 1px solid #E7EBEA;">  
          <td style="border: 0px; width: 40px;" align="center"><input type="checkbox"></td>
          <td style="border-right: 1px solid #EFDADF; border-left: 1px solid #EFDADF; width: 5px;">&nbsp</td>
          <td style="border: 0px; width: 535px; padding: 16px 22px 16px 16px;">Attentively check the file</td>
          <td style="border-left: 1px solid #E7EBEA; width: auto;" align="center">
            <div class="action-task">
              <input style="margin-right: 11px;" type="image" src="/assets/move_task_btn.png">
              <img style="margin-right: 11px;" src="/assets/line_task_action.png">
              <input style="margin-right: 11px;" type="image" src="/assets/edit_task_btn.png">
              <img style="margin-right: 11px;" src="/assets/line_task_action.png">
              <input type="image" src="/assets/del_task_btn.png">
            </div>
          </td>
        </tr> -->
<% end %>

        </tbody>
      </table>


 <% end %>

app/views/lists/new.html.erb
<h1>New list</h1>
 
<%= render 'form' %>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<h2>Tasks</h2>
<%= render @list.tasks %>

 <h2>Add a task:</h2>
<%= render 'tasks/form' %>

<%= link_to 'Back', lists_path %> |
<%= link_to 'Edit', edit_list_path(@list) %>

app/views/tasks/_form.html.erb
<%= form_for([@list, @list.tasks.build]) do |f| %>
  
<p>
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<p>
  <strong>Task:</strong>
  <%= task.task %>
</p>
<p>
  <%= link_to 'Destroy Task', [task.list, task],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/tasks/edit.html.erb
<h1>Editing Task names</h1>
 
<%= form_for ([@list, @task]) do |f| %>
  

<% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', lists_path %>